---
debug_print: true
unix_home_user: ENTER_USERNAME # The user where the client configuration changes in /home/ will be applied to.
mkinitcpio_profile: linux
grub_path: /boot/grub/grub.cfg
samsung_g9_display_port: DP-1
btrfs_submodule_names:
  - name: virtual-machines
    owner: "1000"
    group: "libvirt-qemu"
    mode: "0660"
  - name: games
    owner: "1000"
    group: "1000"
    mode: "0640"
  - name: nextcloud
    owner: "1000"
    group: "1000"
    mode: "0640"
nextcloud_remotes:
  - name: ENTER_REMOTE_NAME
    remote: ENTER_REMOTE_URL
    username: ENTER_NEXTCLOUD_USERNAME
    path: /nextcloud
printer:
  name: brother-dcp1610w
  model: DCP-1610W
  ip: 192.168.1.155 # required, SANE does not allow FQDN.
  # fqdn: brother-dcp1610w.domain.tld # optional
