---
- name: Make sure config directory exists
  become: true
  become_user: "{{ unix_home_user }}"
  file:
    path: "{{ lookup('env', 'HOME') }}/.config/Nextcloud"
    owner: "{{ unix_home_user }}"
    group: "{{ unix_home_user }}"
    state: directory
    mode: "0755"


- name: Put our Nextcloud config file into place
  become: true
  become_user: "{{ unix_home_user }}"
  template:
    src: nextcloud.cfg.j2
    dest: "{{ lookup('env', 'HOME') }}/.config/Nextcloud/nextcloud.cfg"
    owner: "{{ unix_home_user }}"
    group: "{{ unix_home_user }}"
    mode: "0644"

- name: Make sure our Nextcloud local directories exist
  file:
    path: "{{ item }}"
    owner: "{{ unix_home_user }}"
    group: "{{ unix_home_user }}"
    state: directory
    mode: "0750"
  loop: "{{ nextcloud_remotes | map(attribute='path') | list }}"
