---
- name: Make sure autostart directory exists
  become: true
  become_user: "{{ unix_home_user }}"
  file:
    path: "{{ lookup('env', 'HOME') }}/.config/autostart"
    state: directory
    owner: "{{ unix_home_user }}"
    group: "{{ unix_home_user }}"
    mode: "0755"

- name: Add Nextcloud desktop client to autostart applications
  become: true
  become_user: "{{ unix_home_user }}"
  copy:
    src: Nextcloud.desktop
    dest: "{{ lookup('env', 'HOME') }}/.config/autostart/"
    owner: "{{ unix_home_user }}"
    group: "{{ unix_home_user }}"
    mode: "0644"
