---
- name: Install base packages
  pacman:
    name:
      - accountsservice
      - base
      - base-devel
      - bash-completion
      - bind
      - cronie
      - cryptsetup
      - curl
      - device-mapper
      - dnsmasq
      - e2fsprogs
      - git
      - inetutils
      - jfsutils
      - linux
      - linux-firmware
      - linux-headers
      - logrotate
      - lvm2
      - man-db
      - man-pages
      - mdadm
      - nano
      - netctl
      - networkmanager
      - openssh
      - openssl
      - perl
      - python3
      - sudo
      - sysfsutils
      - texinfo
      - usbutils
      - vi
      - wget
      - xfsprogs
    state: present

- name: Cron service running
  systemd:
    name: cronie.service
    state: started
    enabled: true
