---
- name: Install font packages
  pacman:
    name:
      - adobe-source-han-sans-cn-fonts
      - adobe-source-han-sans-jp-fonts
      - adobe-source-han-sans-kr-fonts
      - noto-fonts
      - noto-fonts-extra
      - noto-fonts-emoji
      - noto-fonts-cjk
      - powerline-fonts
    state: present
