---
- name: Install yay
  import_tasks: yay.yaml

- name: Upgrade installed packages
  yay:
    upgrade: true
    update_cache: true

- name: Install base packages
  import_tasks: base.yaml

- name: Install fonts
  import_tasks: fonts.yaml

- name: Install development packages
  import_tasks: development.yaml

- name: Install applications
  import_tasks: applications.yaml

- name: Install virtualization applications
  import_tasks: virtualization.yml
